<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1d7e8c863a119297889d2cf44cc2e826
{
    public static $prefixLengthsPsr4 = array (
        'e' => 
        array (
            'esharsh\\Testcept\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'esharsh\\Testcept\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1d7e8c863a119297889d2cf44cc2e826::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1d7e8c863a119297889d2cf44cc2e826::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1d7e8c863a119297889d2cf44cc2e826::$classMap;

        }, null, ClassLoader::class);
    }
}
